eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  # Configurable URLs for services
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:4200" #Angular app domain
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
            exposed-headers:
              - Authorization  # Expose Authorization header so it's visible to the browser
            allow-credentials: true
      routes:
        - id: school-service-school
          uri: lb://school-service # Load-balanced call to scholl-service
          predicates:
            - Path=/schools/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: school-service-class
          uri: lb://school-service
          predicates:
            - Path=/classes/**
          filters:
            - PrefixPath=/dss/api/v1


        - id: school-service-address
          uri: lb://school-service
          predicates:
            - Path=/addresses/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: school-service-employee
          uri: lb://school-service
          predicates:
            - Path=/employees/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: student-service-student
          uri: lb://student-service
          predicates:
            - Path=/students/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: student-service-guardian
          uri: lb://student-service
          predicates:
            - Path=/guardians/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: student-service-consent
          uri: lb://student-service
          predicates:
            - Path=/consents/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: teacher-service-teacher
          uri: lb://teacher-service
          predicates:
            - Path=/teachers/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: teacher-service-cours
          uri: lb://teacher-service
          predicates:
            - Path=/courses/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: user-service-permissions
          uri: lb://user-service
          predicates:
            - Path=/permissions/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: user-service-roles
          uri: lb://user-service
          predicates:
            - Path=/roles/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: dm-service
          uri: lb://dm-service
          predicates:
            - Path=/documents/**
          filters:
            - PrefixPath=/dss/api/v1

        - id: bff-service
          uri: lb://bff-service
          predicates:
            - Path=/bff/**
          filters:
            - PrefixPath=/dss/api/v1
           # - AddRequestHeader=Authorization, Bearer #{Authorization}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# JWT Properties expiration and refresh times (in milliseconds)
# Secret key
jwt:
  secret:
    key: 8KvVu4Bn2KwBNX1MdnXY6VaRVLekVxurk3aaJxnzdCuZL6AHEL0EnnAOYLZtHWUr
  access:
    token:
      expiration: 1800000 # 30 min in milliseconds for token expiration time
  refresh:
    token:
      expiration: 604800000 # 7 days in milliseconds

