server:
  port: 9090

services:
  context:
    path: dss/api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
spring:
  profiles:
    active: dev
  application:
    name: dss-gateway
  # Configurable URLs for services
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
              - "http://localhost:4200" #Angular app domain
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
            allow-credentials: true
      routes:
        - id: school-service-school
          uri: lb://school-service # Load-balanced call to scholl-service
          predicates:
            - Path=/dss/api/v1/schools/**

        - id: school-service-class
          uri: lb://school-service
          predicates:
            - Path=/dss/api/v1/classes/**

        - id: school-service-address
          uri: lb://school-service
          predicates:
            - Path=/dss/api/v1/addresses/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{Authorization}  # Corrected format

        - id: school-service-employee
          uri: lb://school-service
          predicates:
            - Path=/dss/api/v1/employees/**

        - id: student-service-student
          uri: lb://student-service
          predicates:
            - Path=/dss/api/v1/students/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{Authorization}  # Corrected format

        - id: student-service-guardian
          uri: lb://student-service
          predicates:
            - Path=/dss/api/v1/guardians/**

        - id: student-service-consent
          uri: lb://student-service
          predicates:
            - Path=/dss/api/v1/consents/**

        - id: teacher-service-teacher
          uri: lb://teacher-service
          predicates:
            - Path=/dss/api/v1/teachers/**

        - id: teacher-service-cours
          uri: lb://teacher-service
          predicates:
            - Path=/dss/api/v1/courses/**

        - id: dm-service
          uri: lb://dm-service
          predicates:
            - Path=/dss/api/v1/documents/**

        - id: bff-service
          uri: lb://bff-service
          predicates:
            - Path=/dss/api/v1/bff/**
          filters:
            - AddRequestHeader=Authorization, Bearer #{Authorization}  # Corrected format
# JWT Properties expiration and refresh times (in milliseconds)
# Secret key
jwt:
  secret:
    key: 8KvVu4Bn2KwBNX1MdnXY6VaRVLekVxurk3aaJxnzdCuZL6AHEL0EnnAOYLZtHWUr
  access:
    token:
      expiration: 60000 #1800000 # 30 min in milliseconds for token expiration time
  refresh:
    token:
      expiration: 604800000 # 7 days in milliseconds

